<script lang="ts">
  import { SocketExplorer } from "@workspaces/features";

  // ---- View Model
  import { WebSocketExplorerPageViewModel } from "./WebSocketExplorerPage.ViewModel";
  import { Debounce } from "@common/utils";
  import { isGuestUserActive, user } from "$lib/store";
  import { onDestroy, onMount } from "svelte";
  import type { TabDocument, WorkspaceDocument } from "@app/database/database";
  import { webSocketDataStore } from "@workspaces/features/socket-explorer/store";
  import {
    EnvScopeEnum,
    type EnvDocumentType,
    type EnvExtractedByWorkspaceType,
    type EnvExtractVariableType,
  } from "@common/types/workspace/environment";
  import type { WebSocketData } from "@workspaces/features/socket-explorer/store/websocket";
  export let tab: TabDocument;
  let isLoginBannerActive = false;
  const _viewModel = new WebSocketExplorerPageViewModel(tab);
  const environments = _viewModel.environments;
  const activeWorkspace = _viewModel.activeWorkspace;
  let isGuestUser = false;
  let userId = "";
  let userRole = "";

  isGuestUserActive.subscribe((value) => {
    isGuestUser = value;
  });

  user.subscribe((value) => {
    if (value) {
      userId = value._id;
    }
  });

  /**
   * Find the role of user in active workspace
   */
  const findUserRole = async () => {
    const workspace = await _viewModel.getWorkspaceById(
      tab?.path?.workspaceId as string,
    );
    workspace.users?.forEach((value) => {
      if (value.id === userId) {
        userRole = value.role as string;
      }
    });
  };

  const renameWithCollectionList = new Debounce().debounce(
    _viewModel.updateNameWithCollectionList as any,
    1000,
  );
  let prevTabName = "";
  $: {
    if (tab) {
      if (tab?.name && prevTabName !== tab.name) {
        renameWithCollectionList(tab.name);
      }
      prevTabName = tab.name;
      findUserRole();
    }
  }

  let environmentVariables: EnvExtractedByWorkspaceType;
  let environmentId: string = "";
  let currentWorkspaceId = "";
  let currentWorkspace;

  const activeWorkspaceSubscriber = activeWorkspace.subscribe(
    async (value: WorkspaceDocument) => {
      const activeWorkspaceRxDoc = value;
      if (activeWorkspaceRxDoc) {
        currentWorkspace = activeWorkspaceRxDoc;
        currentWorkspaceId = activeWorkspaceRxDoc.get("_id");
        environmentId = activeWorkspaceRxDoc.get("environmentId");
      }
    },
  );

  /**
   * @description - refreshes the environment everytime workspace changes
   */
  const refreshEnvironment = () => {
    if ($environments && currentWorkspaceId) {
      if ($environments?.length > 0) {
        const filteredEnv = $environments
          .map((it) => {
            return it.toMutableJSON() as EnvDocumentType;
          })
          .filter((elem) => {
            return elem.workspaceId === currentWorkspaceId;
          })
          .filter((elem) => {
            if (
              elem.type === EnvScopeEnum.GLOBAL ||
              elem.id === environmentId
            ) {
              return true;
            }
          });
        if (filteredEnv?.length > 0) {
          let envs: EnvExtractVariableType[] = [];
          environmentVariables = {
            local: filteredEnv[1],
            global: filteredEnv[0],
            filtered: [],
          };
          filteredEnv.forEach((temp) => {
            temp?.variable?.forEach((variable) => {
              if (variable.key && variable.checked) {
                envs.unshift({
                  key: variable.key,
                  value: variable.value,
                  type: temp.type === EnvScopeEnum.GLOBAL ? "G" : "E",
                  environment: temp.name,
                });
              }
            });
          });
          environmentVariables.filtered = envs;
        }
      }
    }
  };

  $: {
    if (environmentId || $environments || currentWorkspaceId) {
      refreshEnvironment();
    }
  }
  onMount(async () => {
    const guestUser = await _viewModel.getGuestUser();
    if (guestUser?.isBannerActive) {
      isLoginBannerActive = guestUser?.isBannerActive;
    }
  });

  onDestroy(() => {
    activeWorkspaceSubscriber.unsubscribe();
  });

  let webSocketData: WebSocketData | undefined;
  webSocketDataStore.subscribe((webSocketMap) => {
    webSocketData = webSocketMap.get(tab?.tabId as string);
  });
</script>

<SocketExplorer
  collections={_viewModel.collection}
  bind:tab={_viewModel.tab}
  bind:userRole
  webSocket={webSocketData}
  {environmentVariables}
  {isGuestUser}
  onUpdateRequestUrl={_viewModel.updateRequestUrl}
  onUpdateRequestParams={_viewModel.updateParams}
  onUpdateHeaders={_viewModel.updateHeaders}
  onUpdateAutoGeneratedHeaders={_viewModel.updateAutoGeneratedHeaders}
  onUpdateMessage={_viewModel.updateMessage}
  onUpdateRequestState={_viewModel.updateRequestState}
  onSaveSocket={_viewModel.saveSocket}
  readWorkspace={_viewModel.readWorkspace}
  onSaveAsSocket={_viewModel.saveAsSocket}
  onCreateFolder={_viewModel.createFolder}
  onCreateCollection={_viewModel.createCollection}
  onUpdateEnvironment={_viewModel.updateEnvironment}
  onRenameCollection={_viewModel.handleRenameCollection}
  onRenameFolder={_viewModel.handleRenameFolder}
  onConnect={_viewModel.connectWebsocket}
  onDisconnect={_viewModel.disconnectWebsocket}
  onSendMessage={_viewModel.sendMessageWebsocket}
  onSearchMessage={_viewModel.searchMessages}
  onDeleteMessage={_viewModel.deleteMessages}
  onUpdateContentType={_viewModel.updateContentType}
  onUpdateMessageBody={_viewModel.updateMessageBody}
  onClearInput={_viewModel.clearInput}
  onUpdateFilterType={_viewModel.updateFilterType}
/>
