name: Development

on:
  push:
    branches:
      - development
  workflow_dispatch:

env:	
  VITE_API_URL: ${{ secrets.VITE_API_URL_DEV }}
  VITE_SPARROW_SUPPORT_EMAIL: ${{ secrets.VITE_SPARROW_SUPPORT_EMAIL_DEV }}
  VITE_SPARROW_OAUTH: ${{ secrets.VITE_SPARROW_OAUTH_DEV }}
  VITE_ENABLE_MIX_PANEL: ${{ secrets.VITE_ENABLE_MIX_PANEL_DEV }}
  VITE_MIX_PANEL_TOKEN: ${{ secrets.VITE_MIX_PANEL_TOKEN_DEV }}
  VITE_TERMS_OF_SERVICE: ${{ secrets.VITE_TERMS_OF_SERVICE_DEV }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: yarn install

    - name: Build app
      run: yarn build

    - name: Deploy to Azure Static Web App
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.MANAGE_DEV_TOKEN }}
        action: "upload"
        app_location: "./dist"
        api_location: ""
